# Generated by Django 2.0.3 on 2019-04-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellth_water', '0002_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='user_id',
            new_name='user',
        ),
    ]
