# Generated by Django 2.0.3 on 2019-04-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellth_water', '0005_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='type',
            new_name='drinktype',
        ),
    ]
